stages:
    - Build
    - Security_Scan
    - Scan_Reporting
    - Housekeeping
    - Deploy_Run
    - Dynamic_Analysis

Compile Application:
    image: maven:3.6.0-jdk-8
    stage: Build
    script:
      - mvn clean package
    artifacts:
      name: verademo_julian_10_build
      paths:
        - target/
      expire_in: 5 week
    cache:
      paths:
        - target/
        - .m2/repository

Build Docker Image:
    image: docker:19.03.8-dind 
    stage: Build
    services:
        - docker:19.03.8-dind
    before_script:
        - docker info
    script:
        - docker pull juliantotzek/verademo1-tomcat

Pipeline Scan Staic Analysis:
    image: veracode/pipeline-scan:latest
    stage: Security_Scan
    only:
        - development
    script:
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${API_ID} -vkey ${API_KEY} --request_policy "VeraDemo Policy" 2>&1 | tee pipeline_scan_policy_output.txt
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${API_ID} -vkey ${API_KEY} --file target/verademo.war --issue_details true --gl_issue_generation true --gl_vulnerability_generation true --policy_file VeraDemo_Policy.json -bf pipeline-basline.json -fjf filtered_results.json 2>&1 | tee pipeline_scan_text_output.txt
    artifacts:
        reports: 
            sast: veracode_gitlab_vulnerabilities.json
        paths:
            - results.json
            - filtered_results.json
            - pipeline_scan_text_output.txt
            - pipeline_scan_policy_output.pipeline_scan_text_output
            - veracode_gitlab_vulnerabilities.json
        when: always
        name: "veracode-pipeline-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: true
    
Policy Scan Static Analysis:
    image: veracode/api-wrapper-java
    stage: Security_Scan
    only:
        - schedules
        - master
    script:
        - java -jar /opt/veracode/api-wrapper.jar -vid ${API_ID} -vkey ${API_KEY}
          -action UploadAndScan -appname "pl_demo" -createprofile false -autoscan true
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" 
          -scantimeout 15 2>&1 | tee policy_scan_output.txt
    artifacts:
        paths:
            - policy_scan_output.txt
        when: always
        name: "veracode-POLICY-SCAN-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: true

Pipeline Scan create new baseline file:
    image: veracode/pipeline-scan:latest
    stage: Scan_Reporting
    only:
        - schedules
        - master
    script:
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${API_ID} -vkey ${API_KEY} --file target/verademo.war -jf pipeline-basline.json 2>&1 | tee pipeline_baseline_file_output.txt
    artifacts:
        paths:
            - pipeline-basline.json
            - pipeline_baseline_file_output.txt
        when: always
        name: "veracode-pipeline-baseline-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: true

Pipeline Scan baseline file commit:
    stage: Housekeeping
    when: on_success
    only:
        - schedules
        - master
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
        - git config --global user.name "${GITLAB_USER_NAME}"
        - git config --global user.email "${GITLAB_USER_EMAIL}"
        - mkdir -p ~/.ssh
        - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    script:
        - git --help
        - git add -f pipeline-basline.json
        - git commit -m "Pipeline Baseline from $CI_COMMIT_SHORT_SHA" || echo "No changes, nothing to commit!"
        - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
        - git push origin HEAD:development
    allow_failure: true
